### ISSUE TITLE
Development on 401 Stable Branch not seen in Moodle Plugins Directory Latest Release

### ISSUE THREAD

**Issue by js-its** [danmarsden/moodle-local_recompletion#110]
Hi,

We use this (and your ObjectFS) plugin on our Moodle instance and on investigation it seems that a fair amount of development has been carried out on these plugins (in the branches marked STABLE) however the latest 'official' releases in the Moodle Plugins Directory are months behind.

So my question is if it is OK to install from the head of the stable branch or should we wait until releases appear in the plugin directory. If the later is there a release schedule that you are aware of?

Many thanks for this and all the work you do on these plugins.

Our current version Moodle 4.1.6+

**Comment by mhughes2k** [comment]
I just noted this as well, we'd normally only pull plugins from the Plugin DB, and with the fix to #78 we're keen to use an updated version!

**Comment by danmarsden** [comment]
I release plugins in the plugins db when I can - but we use git internally to deploy all our plugins so I don't do it as often - I will push out a new release to the plugins db at some point, but the latest stable code of all my plugins (and the Catalyst plugins too) are in git.

thanks!

**Comment by mhughes2k** [comment]
Thanks for the info! Appreciate it

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
