### ISSUE TITLE
Non-matching recompletion type options and help texts

### ISSUE THREAD

**Issue by abias** [danmarsden/moodle-local_recompletion#123]
This may be related to #120 and #111:

Running the MOODLE_401_STABLE branch of 10th november 2024 on a Moodle 4.2 instance, I saw some non-matching settings:

1. In the course settings on /local/recompletion/recompletion.php?id=COURSEID

The recompletion type dropdown has 4 values Disabled, Period, OnDemand and Scheduled:
![grafik](https://github.com/danmarsden/moodle-local_recompletion/assets/1092118/2c3957a7-cfa4-4526-87f6-04ae9f6b6c98)
But the help text does not explain the Scheduled option:
![grafik](https://github.com/danmarsden/moodle-local_recompletion/assets/1092118/bba517b7-ef4b-493f-bcef-1ee6131e9212)

2. In the recompletion default settings on /admin/settings.php?section=local_recompletion

The recompletion type dropdown has 3 values Disabled, Period and Scheduled, but the setting description has 3 different values Disabled, Period, and OnDemand:
![grafik](https://github.com/danmarsden/moodle-local_recompletion/assets/1092118/e6ae6caa-2a44-4a5b-9285-0e2dc61f4e85)

This is, at least, weird.

**Comment by danmarsden** [comment]
Thanks @abias - just pushed a tidy up fix for that now.
