### ISSUE TITLE
4.3 not supported due to scorm table changes.

### ISSUE THREAD

**Issue by cassis07** [danmarsden/moodle-local_recompletion#130]
Hello and thank you for the plugin. Unfortunately, I am experiencing some issues with it.
Moodle is installed in version 4.3. I have set up the plugin for a course. The certificate and entries are supposed to be reset every 10 minutes for testing purposes. The cron-Job comes every 12 Minutes. Unfortunately, it only works sporadically and not all the time. It seems as if it only works the first time. When I complete the course and the test again after resetting and receive a certificate, the course is not successfully reset for a second time.

Here are the messages from the task:

`Execute scheduled task: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion)
... started 12:25:02. Current memory use 26.4 MB.
Debugging increased temporarily due to faildelay of 60
... used 72 dbqueries
... used 0.14786314964294 seconds
Scheduled task failed: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion),Fehler beim Schreiben der Datenbank
Debug info:
Table 'moodleneu2020.mdl_scorm_scoes_track' doesn't exist
DELETE FROM mdl_scorm_scoes_track WHERE userid = ? AND scormid IN (SELECT id FROM mdl_scorm WHERE course = ?)
[array (
  0 => '4772',
  1 => '37',
)]
Backtrace:
* line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
* line 1820 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
* line 108 of /local/recompletion/classes/plugins/mod_scorm.php: call to mysqli_native_moodle_database->delete_records_select()
* line 290 of /local/recompletion/classes/task/check_recompletion.php: call to local_recompletion\plugins\mod_scorm::reset()
* line 119 of /local/recompletion/classes/task/check_recompletion.php: call to local_recompletion\task\check_recompletion->reset_user()
* line 405 of /lib/classes/cron.php: call to local_recompletion\task\check_recompletion->execute()
* line 208 of /lib/classes/cron.php: call to core\cron::run_inner_scheduled_task()
* line 125 of /lib/classes/cron.php: call to core\cron::run_scheduled_tasks()
* line 186 of /admin/cli/cron.php: call to core\cron::run_main_process()`

`Execute scheduled task: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion)
... started 12:24:01. Current memory use 21.5 MB.
... used 70 dbqueries
... used 0.15886998176575 seconds
Scheduled task failed: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion),Fehler beim Schreiben der Datenbank`

`Execute scheduled task: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion)
... started 12:27:03. Current memory use 35.8 MB.
Debugging increased temporarily due to faildelay of 120
... used 2 dbqueries
... used 0.010201930999756 seconds
Scheduled task complete: Prüfen, ob Nutzer Kurs wiederholen müssen (local_recompletion\task\check_recompletion)`

Furthermore, unfortunately, an email reminder for repetition is never sent. All other emails (registration, password reset, certificate, etc.) are sent successfully. Only the reminder for the repetition is not sent out. However, the setting is correctly configured:

![recompletion](https://github.com/danmarsden/moodle-local_recompletion/assets/16940277/00f4c735-2776-49a4-be7e-c1e9f0bf2042)

I would be very grateful for any help.
Thank you and regards,
Sebastian

**Comment by danmarsden** [comment]
Thanks for the report. The code does not currently support the changes in 4.3 to the scorm plugin. Hopefully I'll get a chance to update it soon.

**Comment by cassis07** [comment]
Can we expect an update here in the near future? Thanks

**Comment by danmarsden** [comment]
Hi @cassis07, if you have internal development capabilities, pull requests are always welcome! - I will get to this at some point, however I'm only able to provide timeframes for contracted/paid work. Work I do as a volunteer just has to wait until I get to it - thanks!

**Comment by joshwillcock** [comment]
Hey @danmarsden hopefully I've been able to help with this. - We mustn't PR it into 4.1 as it will break 4.1, but figured you could handle the branch element, hopefully you can get round to checking this over shortly so if any changes are needed I can make them!

Many thanks

**Comment by mpat8121** [comment]
Hi Josh and Dan, 
thanks for your work on this issue. 
I have a Moodle site running 4.3 and I'd like to use this plugin. 
I don't have the technical know-how to assist with the build/test issues that Dan's PR seem to have hit, but was hoping to find out when a merge into the new 403_STABLE branch might be possible?
Thanks!

**Comment by danmarsden** [comment]
@mpat8121 unfortunately answer to questions like "when will X" - are really only possible when you are paying for the time / support. :-)

best I can give to that sort of question is - it's in the top end of the list of things I would like to do when I have time as a volunteer in-between getting the kids sorted for the new school year/other things etc etc :-) - it helps a massive amount that someone has already put the effort in and written a pull request, although the github actions are failing at the moment so it needs a bit more effort (and me to test) before it can be merged in.

**Comment by danmarsden** [comment]
thanks to some work by @joshwillcock  this work has now landed in the 4.3 branch here in githb. - note I will not be publishing this straight away to the moodle.org plugins db (so please don't ask) - we'll leave it here in github only until a few people have run it locally and reported any issues they find.
