### ISSUE TITLE
Problem with quiz attempts not deleting

### ISSUE THREAD

**Issue by jimjudges2** [danmarsden/moodle-local_recompletion#139]
IS there a bug or have we done something wrong - we are using Moodle 4.1 with the following set up (see image) the quiz attempts are not reset - anything obvious we are missing?
![recompletion](https://github.com/danmarsden/moodle-local_recompletion/assets/152416447/5862d188-918e-430e-851c-b3f4f5f32aff)

**Comment by danmarsden** [comment]
It does look like you're using an older version of the plugin, but have you tried manually resetting a user or viewing the cron logs for the task to seee if it reported any issues with the reset?

**Comment by jimjudges2** [comment]
Thanks Dan - sounds like an update may be needed - I know the cron is running but I will see if we can dig deeper - thanks, much appreciated.
