### ISSUE TITLE
Question about archived certificates and reporting

### ISSUE THREAD

**Issue by VOOM108** [danmarsden/moodle-local_recompletion#141]
I saw, that course_certificate is supported now as a plugin in the code, so settings for that are in the recompletion GUI. It has a checkbox, that the old certificates can be archived. What exactly will happen there? Are the archived certificates to be found in a table in the db, or do the actual certificates remain with the user and are simply revoked? Also, while the plugin is there, under datasources, the reporting for the course_certificate does not seem to exist yet. When it does, does it mean I can create a custom report with Moodle's own reporting system, that includes the valid and archived certificate data?

**Comment by danmarsden** [comment]
No - the course_certificate plugin already has it's own concept for archiving of certificates - the data is stored within it's own tables and the recompletion plugin just triggers that process.

We haven't implemented a custom report source for this data within the recompletion plugin - hopefully someone might add one to the course certificate plugin itself at some point. Feel free to reach out privately if you would like fund further development - thanks!

**Comment by VOOM108** [comment]
What table is that exactly where the data of the archived certificates are stored?
