### ISSUE TITLE
Error When Issuing a Recomplete

### ISSUE THREAD

**Issue by lmdengler** [danmarsden/moodle-local_recompletion#147]
Good Afternoon all 

I am new to the plugin and testing it.  I have 2 students enrolled.  I initiate a reset/recomplete and it worked as expected.  Next - recompleted the course as the student.  Next attempted to reset/recomplete the student's activity and I received an error.   
What am I doing wrong? I appreciate anyone's support on this. 
Lisa

![receomplete error](https://github.com/danmarsden/moodle-local_recompletion/assets/159484634/32a352e1-5b59-475d-b30c-b3e34dae1597)

**Comment by danmarsden** [comment]
what version of Moodle are you using and what version of the recompletion plugin do you have installed?

**Comment by lmdengler** [comment]
I am using Moodle Workplace 4.2.5 and the most recent version of the plug-in.  It was installed on our site just last week.

**Comment by danmarsden** [comment]
what do you mean by "most recent" - can you please provide the version number? - the version in moodle.org database is not the most recent - the version in github is always the most recent and it may have some related bug fixes.

note: I have also not tested this plugin in workplace - you may run into other issues with workplace too.

**Comment by lmdengler** [comment]
Good morning - 
I am using the recomplete version 2023111402

**Comment by danmarsden** [comment]
That is not the latest release. Please upgrade to the version from github and try again, thanks.

**Comment by lmdengler** [comment]
Ahhhhh - thank you!  I have asked our hosting vendor (MoodleUS) to install the latest version.  I'll be sure to circle back and let you know if it is working as expected.

**Comment by danmarsden** [comment]
closing as I expect this will have been fixed, but please come back and let me know if you still have issues.

**Comment by lmdengler** [comment]
Good Morning - We installed the latest version of the plugin and I am still experiencing the error.  It appears to occur if you try to use the "recomplete" function on someone who has:

1. completed the course.
2. been selected to recomplete. 
3. completes the course again.
4. is selected to recomplete.

Other helpful information:  
If you select to "continue" after the pink error page (see attachment) is displayed, you re returned to previous page and the only choice is to hit cancel.  If you select "continue", the error page is displayed again.   After hitting "cancel", you are returned to the Participants page.  If you open reports and review activity and course completion, despite the pink error page, the user's course has been reset.  

I asked MoodleUS to upgrade to the latest version and they indicated via email they had.  When I checked, we are at version 2023111402, which is the same version as was installed.  If I go to the Moodle plugins page, this appears to be the latest version.  https://moodle.org/plugins/local_recompletion/versions  

Should I be asking them to get it from somewhere else?  If yes can you give me the link please? 

Thanks so much -
Lisa

![ReComplete error](https://github.com/danmarsden/moodle-local_recompletion/assets/159484634/c7998144-dae6-4abc-9547-2a1491d314b2)

**Comment by danmarsden** [comment]
Tell them to get the version from github(right here.)

The latest version number for the branch that supports moodle 4.2 is:
https://github.com/danmarsden/moodle-local_recompletion/blob/MOODLE_401_STABLE/version.php#L27

**Comment by lmdengler** [comment]
MoodleUS updated the plugin and now the bug issue noted earlier is resolved.  A new issue (and this could be something I am doing) - is the certificate is not archiving.

**Comment by danmarsden** [comment]
thanks for confirming it's sorted - if you track an issue down, please create a new issue, but make sure you are clear which certificate plugin you are using as there are several!!
