### ISSUE TITLE
Feature Request: Force Manual Recompletion

### ISSUE THREAD

**Issue by kgalilio** [danmarsden/moodle-local_recompletion#167]
I am not sure if this option is already available, but it would help to force triggering the course recompletion process manually before the schedueled recompletion date. Sometimes a user or group of users are required to align their course completion date with another activity (not within moodle); having this feature may help synchronise the course completion with those activities.

**Comment by danmarsden** [comment]
To reset an individual response see the "Modify course completion dates" link added to the course settings menu by this plugin. (yes it's a feature included already.)
