### ISSUE TITLE
M4.3 - 2024042200 - error while updating 

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#168]
@danmarsden after upgrade our test side from M4.2 to M4.3 and update the Course Recompletion plugin version 2024042200 we got the error below 

![image](https://github.com/danmarsden/moodle-local_recompletion/assets/16559999/d8429d68-a979-43bf-adbe-cc261082fc56)

We don't have this issue when we install the module for the first time.

**Comment by gemguardian** [comment]
@danmarsden I am not sure but maybe the course was deleted. I should had checked with the database sorry. But I can imagine this is a scenario that can happen.

**Comment by danmarsden** [comment]
thanks @gemguardian I've just pushed a fix through to prevent that one.
