### ISSUE TITLE
issue when upgrading to 2024042200

### ISSUE THREAD

**Issue by bigzooooz** [danmarsden/moodle-local_recompletion#171]
@danmarsden  After upgrading Moodle from  4.3 to 4.4 and trying to upgrade local_recompletion, it throws this error. would you be kind help with this?

![image](https://github.com/danmarsden/moodle-local_recompletion/assets/7108710/80d1b45c-7d60-4966-80ee-2a9e14a589e3)

**Comment by bigzooooz** [comment]
nevermind, i have fixed it on `db/upgrade.php:1049`

**Comment by danmarsden** [comment]
this was also fixed in #169
