### ISSUE TITLE
Plug in cannont reset the Course

### ISSUE THREAD

**Issue by Ka-Va-Mo** [danmarsden/moodle-local_recompletion#173]
Hello,
I've been testing the plug-in for a few days. Unfortunately, it doesn't work.
No activities are reset. Only certificates are deleted and the quiz is reset.
The course is shown as completed in the course completion.
What am I doing wrong? All relevant settings are activated.

**Comment by danmarsden** [comment]
Hi there - not sure sorry - best thing to do would be to take screenshots of your settings, and start a discussion post in the moodle.org forums - including information on the moodle version you are using - hope you figure it out!

**Comment by Ka-Va-Mo** [comment]
thank you for your messages.

I don't have any Videos. I initially only set up a test course with only 3 text sections.

I don't know what I changed, but it works.

I have a question. If I set a period of 365 days, from what point in time do the 365 days apply? From the time of enrollment or from the time the course is completed? I would like the course to always start on January 2nd.

thank you for your support.

**Comment by Ka-Va-Mo** [comment]
and I noticed that the plugin always resets the course after the set date in Task Scheduler and not according to the set period

**Comment by danmarsden** [comment]
Hi @Ka-Va-Mo your questions there are really "how-to" style questions which are best asked in the moodle.org community forums - the github issues tracker here is for reporting issues and feature requests. There are a number of people using this plugin who contribute to discussions in the moodle forums so if you create a post there and explain what you are trying to do there hopefully someone will chime in with some help - as mentioned before, it's a good idea to include screenshots of your recompletion settings in your forum post, along with details on what Moodle version you are using - thanks!
