### ISSUE TITLE
reset period

### ISSUE THREAD

**Issue by Ka-Va-Mo** [danmarsden/moodle-local_recompletion#174]
I noticed that the plugin always resets the course according to the date set in Task Scheduler and not according to the set period time in the configuration. How can I change it, that the period time is the given time.

**Comment by danmarsden** [comment]
Hi there - as mentioned in #173 the best place for "how do I..." questions is the moodle.org community forums - I don't provide one on one support for free here in the issues tracker - the issues tracker is for reporting bugs or feature requests.

You can do what you are asking for - but if you can't figure it out on your own, try asking for help in the forums (I do provide a bunch of support in the forums myself too! 

thanks!
