### ISSUE TITLE
Upgrade fails due to missing 'global $OUTPUT'

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-local_recompletion#187]
Line 1044 has the code echo $OUTPUT->render(....

...in db/upgrade.php

...however, $OUTPUT was never declared as 'global' at the start of the function. Which (worse) makes me think this check for a large number of records was never actually tested :(

https://github.com/danmarsden/moodle-local_recompletion/blob/ff08a5f72bc6e6eab2b012a711cde6748f297804/db/upgrade.php#L1044

https://github.com/danmarsden/moodle-local_recompletion/blob/ff08a5f72bc6e6eab2b012a711cde6748f297804/db/upgrade.php#L32

**Comment by danmarsden** [comment]
weird this hasn't been noticed earlier... I've pushed a global $OUTPUT in there now - pretty sure I did run that through a local test before I merged, but maybe it didn't have the scorm data I thought it did....

**Comment by thepurpleblob** [comment]
I should add that we did re-run this on our big site with the global $OUTPUT added and it was fine. As an aside, whatever it was warning would take a long time didn't seem to take much time at all ;-)

**Comment by danmarsden** [comment]
yeah - I wouldn't expect recompletion to really need the progress bar but it's just pretty much copied from the core SCORM upgrade code.  I wouldn't expect recompletion tables to contain anywhere near the possible data compared with sites that have been using SCORM for a long time.
