### ISSUE TITLE
wrong time despite correct period

### ISSUE THREAD

**Issue by Ka-Va-Mo** [danmarsden/moodle-local_recompletion#189]
Our users student enrolled using the Autoenroll plugin. Each course runs for a duration of 4 weeks for each student.
The recomplition plugin is set with a period of 365 days. Nevertheless, after 4 weeks, all students receive a message that they have to repeat the course. Where is the mistake.

![3](https://github.com/user-attachments/assets/0a65284d-8c52-4001-b0f5-d172030f26d5)
![2](https://github.com/user-attachments/assets/6aee04f5-a740-4cab-8ba5-c1acecf73d5b)
![1](https://github.com/user-attachments/assets/19146ddd-0ea1-4e6b-8796-23647907dd1f)

**Comment by danmarsden** [comment]
2nd checkbox in screenshot at the top - the english language version of that setting is "Reset completion on un-enrolment" - untick that box.
