### ISSUE TITLE
Additional Attempts not possible beyond 10 attempts.

### ISSUE THREAD

**Issue by Lennos** [danmarsden/moodle-local_recompletion#19]
Due to how Attempts Allowed are managed in Moodle Quiz Activity Core (1-10 or unlimited), this plugin doesn't issue additional attempts upon recompletion processing if the users' total attempts > 10.

Appreciate any fix or workaround.

**Comment by danmarsden** [comment]
i haven't been able to reproduce this but I did see some issues related to the quiz reset where there was a missing require resulting in a fatal error in the cron under certain conditions. I've just pushed a fix for this so hopefully this fixes the underlying issue you were seeing. Please let me know if you are still having issues once you update to the latest version of the code.

You might find the new "reset my completion" feature makes this easier to test - allowing the user to reset their own recompletion manually.
