### ISSUE TITLE
Manuly reset the course completion for one user in the moodle/local/recompletion/participants.php page

### ISSUE THREAD

**Issue by bmoschr** [danmarsden/moodle-local_recompletion#195]
Hi Dan,

sadly I can't reset the course completion for one user on the moodle/local/recompletion/participants.php page. Their are no errors on the page, just the alert "Completion for the selected students in this course has been reset." appears and nothing happens to the course completion date of the selected users. In the settings page of the plugin I choosed the option "On demand". I also re-runned the cron job manualy.

Did I missed something? The plugin works perfectly for setting an completion date, but not for reset.

I'm using the latest 401 Version of the plugin and moodle 4.1.13.

Best regards,

Ben

**Comment by danmarsden** [comment]
Sounds like your recompletion settings aren't right - did you expand all the advanced settings on the recompletion settings page and make sure it's being configured to actually do something?

**Comment by bmoschr** [comment]
What did I missed? 
[Screenshot_settings.pdf](https://github.com/user-attachments/files/17093040/Screenshot_settings.pdf)

**Comment by danmarsden** [comment]
That's the site level settings(including default values) - you need to modify the course-level settings.

**Comment by bmoschr** [comment]
I missed that point. Thank you - it works perfectly.
