### ISSUE TITLE
Archive completion data is unchecking itself

### ISSUE THREAD

**Issue by dcrccre** [danmarsden/moodle-local_recompletion#199]
When I enable recompletion for a course and have 'archive completion data' enabled as well... it becomes unchecked after I hit 'Save changes'.

As a result, I don't seem to have any archived completion data in any of my sample/test courses.

I've tried pulling any data from the local_recompletion_cc, local_recompletion_cc_cc, and local_recompletion_cmc tables, but they are all empty.

Any ideas and help would be greatly appreciated.

**Comment by danmarsden** [comment]
What Moodle version, PHP version and database are you using? - I'll see if I can reproduce it.

**Comment by dcrccre** [comment]
Thank you for your help. I will do my best to get you the information you need.

Moodle Version: 3.9
Apache Version | Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.33
DB version: I believe MySQL v8.0.30

**Comment by danmarsden** [comment]
ah... sorry - I don't support Moodle 3.9 - support for 3.9 was also dropped by Moodle 10 months ago.

If you manage to upgrade to a supported release of Moodle, including the latest version of recompletion and still have issues, feel free to raise another issue.
