### ISSUE TITLE
"Do nothing" option IS in fact resetting completion

### ISSUE THREAD

**Issue by adjosh** [danmarsden/moodle-local_recompletion#200]
@danmarsden Hello Dan,

So, I thought setting the SCORM activity to "Do Nothing" and setting Quiz to "Delete existing attempts" and "Archive old atttempts" was going to give me my SCORM activity remaining intact and only the Quiz being reset.
But everything got reset!
[yikes]

What is the "Do Nothing" for then? What does it actually mean?

Moodle 4.1.14 (Build: 20241007) with
Moodle Workplace 4.1.14 (Build: 20241008)

Course recompletion (2023112707)

<img width="906" alt="Screenshot 2024-11-07 at 4 02 01 PM" src="https://github.com/user-attachments/assets/b6273009-9cbb-4149-9d25-26d929058584">

Thanks.

**Comment by danmarsden** [comment]
The tool resets completion information (activity completion) - which will clear the fact that the user "completed" the SCORM activity but shouldn't have deleted the SCORM attempts themselves - did it delete the scorm attempts or just the activity completion record stating they have completed the activity?

**Comment by danmarsden** [comment]
as you haven't responded - I assume it just cleared the activity completion like designed. If you are looking for a tool to automatically delete quiz attempts, but leave all activity completion intact - it's possible this plugin could be extended to do this - if you have internal development capabilities, pull requests are always welcome - if you would like to fund feature development feel free to get in touch privately.

**Comment by adjosh** [comment]
Thank you, Dan.

It did clear the activity everywhere.
I guess I misunderstood the intent of that setting.

I honestly thought “Do nothing” meant do nothing.

We will have to deal with that. All the selected users have to redo all the
course content.
We cannot choose to clear some and leave others.

Got it.

No, sorry, not a developer so can’t help in that regard. Thanks for your
help.

Best Regards,
Sarah
