### ISSUE TITLE
Support for Moodle 4.5 LTS (MOODLE_405_STABLE)

### ISSUE THREAD

**Issue by jhu2452** [danmarsden/moodle-local_recompletion#201]
Hi there!

As recertification is a key requirement for our Moodle project we're looking into leveraging your great work on this plugin.

We are however migrating soon to Moodle 4.5, the current stable LTS release [1].

1) Do you have any plans to add Moodle 4.5 / LTS / MOODLE_405_STABLE support anytime soon?
2) Even without official support, could you recommend running the 4.3 version of this plugin in  Moodle 4.5? Or is this ill-advised?

Appreciated!

[1] https://moodledev.io/general/releases

**Comment by danmarsden** [comment]
@jhu2452 - best thing to do is install the latest version of the plugin available here in github test it and report any specific issues you find to the issues tracker here - feel free to take a look at the exising list of issues to see if there's anything there that you think will be a problem for you.

If you have internal development capabilities - pull requests are always welcome too!
