### ISSUE TITLE
Data base Stucture for ad hock Report

### ISSUE THREAD

**Issue by ecottis** [danmarsden/moodle-local_recompletion#202]
Im looking to write an ad hock report to pull out all the re-completion  dated for learners on a course. Im having issues conecting to the corect data.  Could you let me know where the recompletion date is stored please i.e table name and field. 

Thanking you in advance

**Comment by danmarsden** [comment]
Hi @ecottis the right place to ask for "support/help" questions like this is the moodle.org community forums (I'll try to keep an eye out there too.) - the biggest hint to give you is that all plugins store their table structures in the db/install.xml file.
