### ISSUE TITLE
Feature Request: Reset H5P Activities

### ISSUE THREAD

**Issue by karpadiem** [danmarsden/moodle-local_recompletion#21]
Very excited to find your plugin! However, in my testing it looks like it does not reset activities created with the [H5P Interactive Content plugin](https://moodle.org/plugins/mod_hvp).

Any chance this can be implemented? Or guidance on how I might be able to hack it myself?

**Comment by dmitriim** [comment]
Would be nice to implement archiving of mod_hvp data as part of this issue.

**Comment by dmitriim** [comment]
Hey @karpadiem !
I have created PR for this feature. See https://github.com/danmarsden/moodle-local_recompletion/pull/102
If you can test  that would be awesome.

**Comment by dmitriim** [comment]
This has been implemented and merged to 3.11+ and 4.1+ versions, however let's merge this bug https://github.com/danmarsden/moodle-local_recompletion/pull/108 before closing this issue.
