### ISSUE TITLE
While running the cron getting error 

### ISSUE THREAD

**Issue by sirisha47** [danmarsden/moodle-local_recompletion#25]
I have scheduled the all the cron's  and everything successfully completed for the past days, but now a days having issue with the recompletion cron, please look on the below content that i taken from the cron log file(First its printed the task completed and then task failed printing) 

Can you please help me to find out the issue, because of this other crons also not running.

Execute scheduled task: Check for users that need to recomplete (local_recompletion\task\check_recompletion)
... started 22:30:44. Current memory use 49.7MB.
... used 112 dbqueries
... used 3164.0160620213 seconds
Scheduled task complete: Check for users that need to recomplete (local_recompletion\task\check_recompletion)
... used 113 dbqueries
... used 3164.0176432133 seconds
Scheduled task failed: Check for users that need to recomplete (local_recompletion\task\check_recompletion),Error reading from database
!!! Error reading from database !!!

**Comment by danmarsden** [comment]
What version of Moodle and what version of the recompletion plugin? - are you using the latest code?

If you are using the latest code, please enable debugging in your cron using:
$CFG->showcrondebugging = true;

then run it again and get the full error trace.

thanks,

**Comment by sirisha47** [comment]
Thanks Danmarsden,
Version details:
$plugin->version   = 2019052900;
$plugin->release   = '1.5';

We are not using the latest code and we are good with existing feature and we enabled the debug and try to run the cron that time we didn't get issue. The issue occur only on master cron run.

1. First its printed the task completed message and print the task failed message again.(But actually the cron task is completed successfully as we have analysed the database processed records)
2. Also it throwing the "error reading from database" error.

**Comment by danmarsden** [comment]
thanks - please update to the latest version, and then if you get this issue again, please turn the crondebugging setting on and provide the full trace so I can investigate further. It's possible this has already been fixed in a newer release.
