### ISSUE TITLE
Feature request: LTI provider 

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#30]
We love the way this plugin is working and how we can use it in courses. 
And now we want to implement it within our LTI provider courses in Moodle 3.5, 3.8 and 3.9.

I did a test to see if it would work and if not what is needed. 
And the even though the Course Recompletion plugin nicely removes the grade, the LTI provider saves in a separated table "enrol_lti_user" the last grade send.

Due to this, whenever a new grade is the same as in the last_grade in the Enrol_lti_User table de cron job LTI Grade sync, skips the grade and is not sending it towards the LTI consumer. 
In my test, every higher and lower grade is being send, it just refuses to send the “same grade”. 

I understand why this is build in from an LTI Provider point of view, and it does not seem to be logically to make a change there. 
But for re completing a Moodle course using the LTI provider tool, we will need it to work. 
 
To make it work, I would suggest to build in an new (extra) functionality in the Course Recompletion plugin similar to the Quiz, SCORM and Assignement options for the LTI Provider (Moodle standard!) in the ADVANCED section.
 
The setting would be similar to the other settings: 
 
LTI Provider last grade send:

- Do nothing (last grade stays in the table enrol_lti_user)

- Delete last grade send (last grade in table enrol_lti_user will be removed)

- Archive last grade send (last grade will be removed in table enrol_lti_user, but will be logged in local_recompletion_ltia (or table name that seems fitting to the developer) in a similar way as the Quiz module : LTI TOOL ID, Moodle USER ID, lastaccess, modified, course)

**Comment by danmarsden** [comment]
Thanks - yes, sounds like a good plan!!
there's probably a longer term need to restructure some of the code a bit, but simply adding some new "reset_lti" function in the check_recompletion class (along with the settings/UI stuff) is probably enough for now.

One day I might look at making it more pluggable so it can "detect" plugins that support recompletion or you can drop in specific classes for each supported plugin. My longer term vision was to have the plugins themselves implement functions that we could call from recompletion but... lot more work for that!

**Comment by gemguardian** [comment]
hi Dan, 
Luuk Verhoeven is going to start working on this issue, I will test the new version before he will do a request to you. 

I think it is interesting idea to let it "dectect" plugins that support recompletion. Might be a good MUA project. :)
Gemma

**Comment by gemguardian** [comment]
hi Dan, 
I have tested the changes that Luuk made, and I can see that the LTI grade is being "removed" from the enrol_Lti table when I use the setting "reset LTI grades". 

When I am using the setting "Achive completion data", the information on the LTI grade information is being archived to -	local_recompletion_ltia

We are looking forward to your feedback. 
Thank you
Gemma

**Comment by danmarsden** [comment]
Hi @gemguardian @luukverhoeven, I've finally had a chance to look at the latest patch and have now merged it in! - thanks for the PR!
I did add an extra patch on top that allows the teacher to decide if the LTI data needs to be archived or not (like it does for quiz/scorm)
sorry for taking so long to get this into the main branch!

**Comment by gemguardian** [comment]
Thank you @danmarsden

**Comment by luukverhoeven** [comment]
@danmarsden Thanks for the merge!
