### ISSUE TITLE
Possible to upload or insert "completions" from another LMS?

### ISSUE THREAD

**Issue by davidpesce** [danmarsden/moodle-local_recompletion#31]
I'm wondering if it's possible to insert completion data (in the same format as the local_recompletion_cc table). My use case is for adding completion data from another LMS.

**Comment by danmarsden** [comment]
I don't see why it wouldn't be technically possible - although I would wonder why you were using recompletion to do this... particularly as we don't have any reporting built in to this plugin, so you could just as easily drop it in a custom table and write your own report on that data. I also can't see this being anything I would spend time on myslef (writing an import script to pull in completions from an external source.)

**Comment by davidpesce** [comment]
For ease of use (single report for managers), I added it to local_recompletion_cc table. Thank you!
