### ISSUE TITLE
Bugs using plugin whit oracle database

### ISSUE THREAD

**Issue by polder** [danmarsden/moodle-local_recompletion#33]
Into table local_recompletion_config fild "value" is translated to "clob" on oracle database due to using "text" in install.xml as type for that colum. Having value as clob, breaks the query at the biginning execute () function of scheduled task.

Similar issue on query:
SELECT DISTINCT a. *
                       FROM {assign} a
                       JOIN {assign_submission} s ON a.id = s.assignment
                      WHERE a.course =? AND s.userid =?
of rest_assign funciton. Having "distinct" into select breaks the query due to a clob field in assign table. Maybe using only a.id as select fix this problm considering that "id" is the only field used in that pice of code.

**Comment by danmarsden** [comment]
Thanks for the report - feel free to submit a pull request to help resolve this.

**Comment by danmarsden** [comment]
closing this as "won't fix" - Moodle is dropping upstream support for Oracle and it's not something I plan to spend any time on either - thanks!
