### ISSUE TITLE
Other plugins impelmetnation

### ISSUE THREAD

**Issue by lukascelinak** [danmarsden/moodle-local_recompletion#35]
Hi, i have solution for archives,
if would not be beter to storage all archived data in one table, as json data, for example:

quiz->idnumber= array(quiz_attempts->idnumber= array("quiz_attempt_row"),)
ad so, 
scheme
module->id=array_of_archived_tables(module_table=table_row);

**Comment by danmarsden** [comment]
What problem would that solve? How would you report on the json data?

When this table gets big it would be really hard to work with as you would have to get all records from the table, decode json and then filter it to find the data wanted in the report.

The better solution would be to implement archival support into each activity plugin.

**Comment by lukascelinak** [comment]
I agree with implementing of archival support into each activity plugin,
I
 had implemented it in my own plugins via archived / deleted atribute in each table, where im storaging user attempts or data for grading and completion.

But how to do it for core LMS Moodle plugins? 

I just tried json for lessson module (3 tables) but lesson is really messy in db, that should make problems with storage in future, like you said.

**Comment by danmarsden** [comment]
We'd need to push the code into the core Moodle release - (quite a big project)

I'm closing this off as I don't think json encoding is going to help anything here - happy to review pull requests with improvements though (still need to get to that LTI pull request... hopefully this week or next!)
