### ISSUE TITLE
CourseRecompletion in course with multiple LTI Tools 

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#42]
I jumped into an issue with the CourseRecompletion when used in a course with multiple LTI Tools. It did not seem to save data in the  local_recompletion_ltia and did not clean the finalgrade in the enrol_lti table. 

I have asked @luukverhoeven to take a look at it and he fixed the issue and will send in a push request. 
It would be great if this could be checked/accepted as soon as possible.

Gemma

**Comment by danmarsden** [comment]
sounds great - @luukverhoeven the code has gone through a decent restructure now - the bulk of the lti work is now in here:
https://github.com/danmarsden/moodle-local_recompletion/blob/MOODLE_311_STABLE/classes/activities/lti.php

**Comment by luukverhoeven** [comment]
@danmarsden Thanks, I noticed the restructure, nice work! 
Just created two pull request for MOODLE-39 and MOODLE-311. It goes through all the LTI tools instead of one.

Can you validate the code and approve, if it's ok?

**Comment by danmarsden** [comment]
Looks good thanks @luukverhoeven  - I've merged that in!

**Comment by gemguardian** [comment]
Thank you @luukverhoeven and @danmarsden .
