### ISSUE TITLE
Sorting CourseCompletion

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#47]
Hi 
When I go to "Modify Course Completion Dates" and I click with my mouse on the colum "Course completion" (last column)  for sorting. 

I receive get the following error messages

Moodle 3.9
Versions plugin: 2021092000 (2021092000)

![image](https://user-images.githubusercontent.com/16559999/140756834-8b3a52c1-fae1-4f40-9236-3a318fb7f50d.png)

**Comment by danmarsden** [comment]
thanks for the report - pull requests are always welcome :-)

**Comment by jstilwell** [comment]
Hello, just wanted to leave a comment that we're also seeing this stack trace.

**Comment by dmcdonaldak** [comment]
We are running into this error also.
