### ISSUE TITLE
Recompletion based on last date or option to set a calendar period as the recompilation timeframe.

### ISSUE THREAD

**Issue by rmeske** [danmarsden/moodle-local_recompletion#51]
Hello,

We have a situation where a course needs to be completed yearly during a set period of time regardless of when the course was last completed.  This situation comes up when a new hire is trained outside of the required timeframe during their first calendar year, but the following calendar year they need to complete the course during the set period of time, which could be just a month from the last time.

Is this in the roadmap, or is there a way to accomplish this that I am not seeing?  

We are running Moodle 3.9.6 and plugin version 2021092000.

Regards,
Ron

**Comment by danmarsden** [comment]
Hey Ron! - I don't typically have time for any feature development on my plugins that isn't funded, but you can manually trigger a recompletion for users as the teacher by going to the "Modify course completion dates" page in the course settings.

thanks!

**Comment by rmeske** [comment]
Hi Dan!  I wasn't sure if there were any plans on modifying this.

Just to clarify how the Modify course completion dates will impact this plugin.  For example, take the following scenario:

- A course needs to be recompleted every January
- A user completes the course in November 2021
- Should the completion date for that user be set to January 2021 or January 2022

What happens to the reporting when a completion date is set?

It would be good if you could clarify this in the wiki.

**Comment by danmarsden** [comment]
I thought there was a bulk reset completion link somewhere - I don't have this runinng locally right now - maybe I only added the ability to reset individual users and bulk change the date rather than bulk reset?

if so - that wouldn't be too hard to add - I'd just visit the list in januaray and manually hit "reset all users" for the course.

**Comment by rmeske** [comment]
There is the capability to select multiple users and then reset the completion date.  However, it does not really explain what that does to the students record and how it impacts reporting, if at all.

**Comment by danmarsden** [comment]
yeah - I think what we need to do is add a "reset all" option in that page rather than setting a previous completion date... something to do one day...

**Comment by danmarsden** [comment]
we've added a new recompletion type that allows for a calendar period to be set - eg a regular recompletion cycle rather than a fixed date.
