### ISSUE TITLE
M40 Local Recompletion does not show "run now" in Tasks

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#53]
Version:  20220324002022032400
Moodle: 4.0.2
PHP 7.4

Site administration > Server > Scheduled Tasks

In previous versions of Moodle we could click on "Run now" if properly configured in Moodle. 
The run now options has dissapeared in M4.0

![image](https://user-images.githubusercontent.com/16559999/180833505-653da12b-6a09-4926-bb09-414232a8f127.png)

**Comment by danmarsden** [comment]
yeah - I think that's really a bug in Moodle - the "run now" bit is hidden for plugins that are not enabled, but local plugins have no way to state if they are actually enabled or not.

I think the solution is to modify the core\pluginfo\local class to add a get_enabled_plugins() function and just return all local plugins in the site - but that's something we'd need to look at fixing in Moodle upstream (there's nothing I can do within this plugin to fix it afaik)

**Comment by gemguardian** [comment]
Do you know if there is already a tracker on this for Moodle? I could not find one yet but just want to be sure before I create on.

**Comment by danmarsden** [comment]
not sure sorry - but it's also an issue with plagiarism plugins as the base plagiarism class doesn't implement the get_enabled_plugins() function either.

**Comment by gemguardian** [comment]
Hmm , well I have ceated a tracker (https://tracker.moodle.org/browse/MDL-75308) 

Not sure though if have checked the right component/s.

**Comment by danmarsden** [comment]
closing this as it's being resolved in core.
