### ISSUE TITLE
Assignments history keeps reapearing for submitions even if deleted on recompletion.

### ISSUE THREAD

**Issue by ecottis** [danmarsden/moodle-local_recompletion#54]
There are a couple of major issues (bugs) that I have detected.

1. All Assignments history keeps reappearing for submissions even if deleted on recompletion.  
2. It then then sends out multiple email messages requesting the student to completes the assignment one for each old  previous attempt making the plugin virtually unusable.

This even happens if you delete all submissions one a new submission is reset the old ones reappear as though they are being restored.  It would not be all bad if it did not send out multiple emails to the learners.   

 I’m using Moodle 4.2 and the latest version of the plugin.

![image](https://user-images.githubusercontent.com/67025862/183508989-1ab8c6c6-6acd-4931-951c-214c5c9ba132.png)

**Comment by danmarsden** [comment]
can you please add a screenshot of your recompletion settings, and also provide information on what process you're using to send the " email messages requesting the student to completes the assignment"

thanks

**Comment by ecottis** [comment]
Hi Dan

Thanks for pointing me in the direction of the email system.  After investigation it appears that it may be the email plugin I was using, 'Welcome Email' that may be causing the issue.  I have uninstalled this and will rewrite the courses to see if this resolves the issue.  Nevertheless, thanks for getting back to me.   

Once I have remastered the courses and used the recompletion a few times to test I will let you know if there is still an issue.

Once again thanks for all the hard work and support given.
Regards 
Eddie

**Comment by danmarsden** [comment]
cool - closing for now, but please create a new issue if you find the assignment recompletion isn't working as expected - depending on your recompletion settings it should retain all previous historical attempts within the assignment UI and just give users a new attempt.
