### ISSUE TITLE
Database error selecting 'Modify course completion dates'

### ISSUE THREAD

**Issue by thepurpleblob** [danmarsden/moodle-local_recompletion#56]
Version 2022032400

To reproduce...

- Click the 'Modify course completion dates' column
- Try to sort by the 'Course completion' column. This comes up in a pop up 

The page can no longer be displayed. I'm guessing that clearing a cache may fix it but I haven't tried

Debug info: Unknown column 'coursecompletion' in 'order clause'
SELECT COALESCE(ul.timeaccess, 0) AS lastaccess , u.id, u.username, u.idnumber, u.email, u.picture, u.firstname, u.lastname, u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename, u.imagealt, ctx.id AS ctxid, ctx.path AS ctxpath, ctx.depth AS ctxdepth, ctx.contextlevel AS ctxlevel, ctx.instanceid AS ctxinstance, ctx.locked AS ctxlocked
FROM (SELECT DISTINCT udistinct.id
FROM mdl_user udistinct
JOIN mdl_user_enrolments ue ON ue.userid = udistinct.id
JOIN mdl_enrol e ON e.id = ue.enrolid
AND e.courseid = ?
WHERE udistinct.deleted = 0 AND udistinct.id <> ?
) targetusers
JOIN mdl_user u ON u.id = targetusers.id
LEFT JOIN mdl_user_lastaccess ul ON (ul.userid = u.id AND ul.courseid = ?)
LEFT JOIN mdl_context ctx ON (ctx.instanceid = u.id AND ctx.contextlevel = ?)

ORDER BY coursecompletion ASC, lastname ASC LIMIT 0, 20
-- line 117 of /user/classes/table/participants_search.php: call to mysqli_native_moodle_database->get_recordset_sql()
-- line 421 of /user/classes/table/participants.php: call to core_user\table\participants_search->get_participants()
-- line 162 of /local/recompletion/classes/table/participants.php: call to core_user\table\participants->query_db()
-- line 174 of /local/recompletion/participants.php: call to local_recompletion\table\participants->out()
[array (
0 => '8283',
1 => '1',
2 => '8283',
3 => 30,
)]

**Comment by danmarsden** [comment]
thanks for the reminder - I'd forgotten to come back and fix that - fix pushed!
