### ISSUE TITLE
Recompletion basato sul mancato superamento del quiz

### ISSUE THREAD

**Issue by salutesicilia** [danmarsden/moodle-local_recompletion#57]
Ciao,
potresti prevedere il Recompletion basato sul mancato superamento del quiz?
Grazie!

**Comment by danmarsden** [comment]
It's not something that is currently supported but anything is possible, feel free to reach out privately if you would like to fund any development.

Thanks

**Comment by salutesicilia** [comment]
Ciao, potresti dirmi se puoi sviluppare questa modifica? Quanto costa finanziare questa modifica?Fammi sapere
Grazie!
AVVISO DI RISERVATEZZA
Il testo e gli eventuali documenti trasmessi contengono informazioni riservate al destinatario indicato. La seguente e-mail è confidenziale e la sua riservatezza è tutelata legalmente dalle normative vigenti. La lettura, copia od altro uso non autorizzato o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono  rigorosamente vietate. Se si ritiene di non essere il destinatario di questa mail, o se si è ricevuto questa mail
per errore, si prega di darne immediata comunicazione al mittente e di provvedere immediatamente alla sua distruzione.

NOTICE OF CONFIDENTIALITY
The text and any documents provided contain information reserved for the recipient. The following e-mail is confidential and its confidentiality is legally protected by law. Reading, copying or other unauthorized use or any other actions arising from knowledge of this information is strictly prohibited. If you think not to be the recipient of this message, or if you have received this e-mail in error, please immediately notify the sender and take immediate action to its destruction. 

    Il sabato 27 agosto 2022 02:44:03 CEST, Dan Marsden ***@***.***> ha scritto:  
 
 


It's not something that is currently supported but anything is possible, feel free to reach out privately if you would like to fund any development.

Thanks

**Comment by danmarsden** [comment]
@salutesicilia - please reach out privately via email rather than using the github issues tracker if you would like to discuss financing development - thanks!

**Comment by salutesicilia** [comment]
Ciao, potresti dirmi se puoi sviluppare questa modifica? Quanto costa finanziare questa modifica?Grazie!

AVVISO DI RISERVATEZZA
Il testo e gli eventuali documenti trasmessi contengono informazioni riservate al destinatario indicato. La seguente e-mail è confidenziale e la sua riservatezza è tutelata legalmente dalle normative vigenti. La lettura, copia od altro uso non autorizzato o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono  rigorosamente vietate. Se si ritiene di non essere il destinatario di questa mail, o se si è ricevuto questa mail
per errore, si prega di darne immediata comunicazione al mittente e di provvedere immediatamente alla sua distruzione.

NOTICE OF CONFIDENTIALITY
The text and any documents provided contain information reserved for the recipient. The following e-mail is confidential and its confidentiality is legally protected by law. Reading, copying or other unauthorized use or any other actions arising from knowledge of this information is strictly prohibited. If you think not to be the recipient of this message, or if you have received this e-mail in error, please immediately notify the sender and take immediate action to its destruction. 

    Il sabato 27 agosto 2022 02:44:03 CEST, Dan Marsden ***@***.***> ha scritto:  
 
 


It's not something that is currently supported but anything is possible, feel free to reach out privately if you would like to fund any development.

Thanks

**Comment by scara** [comment]
Ciao @salutesicilia,
> Ciao, potresti dirmi se puoi sviluppare questa modifica? Quanto costa finanziare questa modifica?Grazie!

@danmarsden ti ha già risposto in inglese:
> please reach out privately via email rather than using the github issues tracker if you would like to discuss financing development - thanks!

Devi quindi proporre la tua richiesta in inglese e discuterla con lui in privato scrivendogli all'indirizzo email che Dan mette a disposizione per le comunicazioni; lo trovi nel suo sito [danmarsden.com](https://danmarsden.com/blog/contact/) che è indicato nel [suo profilo GitHub](https://github.com/danmarsden):

> My address is my first name @ the domain name of this site.

Lo ha (de)scritto così per evitare troppo SPAM, se scritto esplicitamente: è però facile scoprire il suo indirizzo mail - `dan` è il suo nome e il dominio del sito te lo ho scritto sopra.

HTH,
Matteo

**Comment by salutesicilia** [comment]
ti ringrazio per il tuo supporto.Cordiali saluti.Antonio
AVVISO DI RISERVATEZZA
Il testo e gli eventuali documenti trasmessi contengono informazioni riservate al destinatario indicato. La seguente e-mail è confidenziale e la sua riservatezza è tutelata legalmente dalle normative vigenti. La lettura, copia od altro uso non autorizzato o qualsiasi altra azione derivante dalla conoscenza di queste informazioni sono  rigorosamente vietate. Se si ritiene di non essere il destinatario di questa mail, o se si è ricevuto questa mail
per errore, si prega di darne immediata comunicazione al mittente e di provvedere immediatamente alla sua distruzione.

NOTICE OF CONFIDENTIALITY
The text and any documents provided contain information reserved for the recipient. The following e-mail is confidential and its confidentiality is legally protected by law. Reading, copying or other unauthorized use or any other actions arising from knowledge of this information is strictly prohibited. If you think not to be the recipient of this message, or if you have received this e-mail in error, please immediately notify the sender and take immediate action to its destruction. 

    Il sabato 3 settembre 2022 11:32:36 CEST, Matteo Scaramuccia ***@***.***> ha scritto:  
 
 


Ciao @salutesicilia,


Ciao, potresti dirmi se puoi sviluppare questa modifica? Quanto costa finanziare questa modifica?Grazie!


@danmarsden ti ha già risposto in inglese:


please reach out privately via email rather than using the github issues tracker if you would like to discuss financing development - thanks!


Devi quindi proporre la tua richiesta in inglese e discuterla con lui in privato scrivendogli all'indirizzo email che Dan mette a disposizione per le comunicazioni; lo trovi nel suo sito danmarsden.com che è indicato nel suo profilo GitHub:


My address is my first name @ the domain name of this site.


Lo ha (de)scritto così per evitare troppo SPAM, se scritto esplicitamente: è però facile scoprire il suo indirizzo mail - dan è il suo nome e il dominio del sito te lo ho scritto sopra.

HTH,
Matteo

**Comment by danmarsden** [comment]
Hi Pezillo, I've just responded to your email, hopefully you received it.

thanks,
