### ISSUE TITLE
Changing course recompletion settings for plugins (advanced section) doesn't appear to work

### ISSUE THREAD

**Issue by Limekiller** [danmarsden/moodle-local_recompletion#58]
I feel like I must be missing something here, but I've reproduced this issue on two Moodle sites. It looks like, when making changes to the course-level recompletion settings for specific plugins (Course > Course Recompletion > Advanced), the changes are not actually saved in the database. 
- For example, if I go to this page and set the form as below:
![image](https://user-images.githubusercontent.com/33644013/195659708-9dfa43dc-0116-4033-b7fb-f6b844adfbfc.png)
- When I hit save and come back to the page, the settings are not saved:
![image](https://user-images.githubusercontent.com/33644013/195659940-46fdac18-4254-450a-9cbb-76c2e4a8acf0.png)

This seems to be because of the way the plugin tries to set these settings in recompletion.php. The code gets a list of the supported plugins, and then iterates over that list trying to grab the relevant settings from the form data using the plugin name. The problem is that the list returned by local_recompletion_get_supported_plugins() does not match the plugin names given by the form data. Here's an example of the form data that might be passed:

```
{
  ["enable"]=>
  string(1) "1"
  ["recompletionduration"]=>
  int(0)
  ["mform_isexpanded_id_emailheader"]=>
  int(0)
  ["recompletionemailsubject"]=>
  string(0) ""
  ["recompletionemailbody"]=>
  string(0) ""
  ["mform_isexpanded_id_advancedheader"]=>
  int(1)
  ["deletegradedata"]=>
  string(1) "1"
  ["assign"]=>
  string(1) "0"
  ["questionnaire"]=>
  string(1) "1"
  ["quiz"]=>
  string(1) "1"
  ["scorm"]=>
  string(1) "1"
  ["submitbutton"]=>
  string(12) "Save changes"
  ["course"]=>
  int(13)
  ["forcearchive"]=>
  int(0)
}
```

And here's the setnames variable that gets built from the above mentioned function: 

```
{
  [0]=>
  string(6) "enable"
  [1]=>
  string(20) "recompletionduration"
  [2]=>
  string(15) "deletegradedata"
  [3]=>
  string(21) "archivecompletiondata"
  [4]=>
  string(23) "recompletionemailenable"
  [5]=>
  string(24) "recompletionemailsubject"
  [6]=>
  string(21) "recompletionemailbody"
  [7]=>
  string(11) "assignevent"
  [8]=>
  string(10) "mod_assign"
  [9]=>
  string(17) "archivemod_assign"
  [10]=>
  string(7) "mod_lti"
  [11]=>
  string(14) "archivemod_lti"
  [12]=>
  string(17) "mod_questionnaire"
  [13]=>
  string(24) "archivemod_questionnaire"
  [14]=>
  string(8) "mod_quiz"
  [15]=>
  string(15) "archivemod_quiz"
  [16]=>
  string(9) "mod_scorm"
  [17]=>
  string(16) "archivemod_scorm"
}
```

As you can see, the plugin names don't match. The plugin will try to get a value by doing $data->$name -- for example, $data->mod_quiz -- but this doesn't exist; instead, it would need to be $data->quiz.

**Comment by danmarsden** [comment]
Thanks for the great report and debugging you provided - was quite easy to reproduce and fix based on the analysis you had already performed! - this was a regression caused by #55 that I missed while testing the pull request - sorry about that! - I've pushed through a fix now, let me know if you get a chance to test it and it works and I'll look at pushing the updated version to the plugins db! - thanks again!

**Comment by Limekiller** [comment]
Thanks, Dan -- looks like it works!
