### ISSUE TITLE
Support for Choice activity

### ISSUE THREAD

**Issue by blanderson22** [danmarsden/moodle-local_recompletion#59]
We have quiz that has a restriction configured that requires 2 choice activities to be complete before the quiz can be accessed. (The choice activities are there for the purpose of the student agreeing to a policy and confirming they've read the instructions.) 

What we're experiencing is that the recompletion plugin is not resetting the activity completion for the purpose of the restriction. The student visits the course for their second enrollment and the 2 choice activities still appear to the student as having been complete, however, in the activity completion report they do not have check marks for those activities. 

The result is that the student cannot complete the activity again, but also the quiz will not allow them access because the quiz doesn't consider the activities complete to satisfy the restriction requirement.

**Comment by danmarsden** [comment]
thanks - this plugin doesn't currently support the deleting of choice activity data which would probably be required to support this scenario. If you have internal development capabilities, pull requests are always welcome! - thanks.

**Comment by aduranterres** [comment]
Thanks Dan. I am working with Bridgette on this. I have created a pull request. Please let me know if you need me to make any changes. Thank you!

**Comment by danmarsden** [comment]
this was merged in a few months ago.
