### ISSUE TITLE
option to delete user activity in modules or allow extra attempts

### ISSUE THREAD

**Issue by danmarsden** [danmarsden/moodle-local_recompletion#6]
should we provide the ability to delete content within specific modules? - deleting quiz attempts/assignments/SCORM attempts.

my current thoughts are "no we shouldn't" but maybe we could add support to allow the number of allowed attempts to be bumped... giving students the ability to submit a new attempt to some activities that support it.

**Comment by laithgate** [comment]
No, it should be retained as this can be used for audit purposes - especially if there is a need for annual refresher training.

**Comment by danmarsden** [comment]
thanks - if we did allow this it would be a setting that the teacher/admin could control, another LMS similar to Moodle that implements a similar feature deletes the user activity data within certain activities like SCORM - but I'd definitely prefer not to do that as our default behaviour.

**Comment by danmarsden** [comment]
@adamrobertbacon has pushed some improvements to this - allowing the teacher to decide if certain data should be deleted.
