### ISSUE TITLE
No Archive completion data stored in DB

### ISSUE THREAD

**Issue by blanderson22** [danmarsden/moodle-local_recompletion#60]
I recently discovered that the recompletion tables are empty even though I'm forcing the archival of completion data in the plugin's global settings. I know that we've had several completion resets happen, both in my testing and actual students, so that confirms the plugin is running. I also have the scheduled task set to run every 5 minutes while I'm testing its function. 

I'm attaching a screenshot of my global plugin settings.

<img width="1267" alt="Screen Shot 2022-12-22 at 12 23 48 PM" src="https://user-images.githubusercontent.com/2252602/209192016-55044ccc-b830-4324-94eb-27faeb15f289.png">

**Comment by danmarsden** [comment]
I suspect this only works for "new" courses being set to use recompletion, or if you save the recompletion settings page after ticking the "force completion" checkbox.

Did you enable recompletion in some courses before ticking that box? - can you try editing the course recompletion settings page and hitting save to see if that fixes it?
