### ISSUE TITLE
**new feature** in bulk resett all completion

### ISSUE THREAD

**Issue by gemguardian** [danmarsden/moodle-local_recompletion#63]
Right now you can do a bulk action  **change completion date for selected users** -it would be nice to also have the option for a bulk action ** reset all completion for selected users** on the same page (/local/recomplation/participants (modify course completion dates)

**Comment by jwtacoustic** [comment]
Is there a way to reset all users data, not just course by course?

**Comment by danmarsden** [comment]
that's not something currently supported - this plugin works inside a course - not at a site level.

**Comment by gemguardian** [comment]
Hi Dan Yannick(@mixedfruitjuice ) will take a look at it

**Comment by gemguardian** [comment]
@danmarsden I did do a few user tests I it worked for me - I am leaving the code check up for you :)

**Comment by danmarsden** [comment]
this has now been merged into the MOODLE_311_STABLE branch - thanks everyone!
