### ISSUE TITLE
add support for certificate plugins.

### ISSUE THREAD

**Issue by VOOM108** [danmarsden/moodle-local_recompletion#64]
I read in many forum threads about recompletion, that resetting the certificates with a recompletion was something asked for a lot and planned to implement. In the docs it is not mentioned at all, though. 

Is there a way or a workaround to issue new certificates (coursecertificate or customcertificate) when the course is reset for a student and the course or an activity is completed again? 

As I found, it seems that coursecertificate does not issue a new certificate if one exists already, even if it is expired as a consequence of its own settings. 

With badges I understand, that badges are something earned and built upon, but certificates are a different thing. 

Is there a way to solve this? 

(Usually the recommendations are that one could just set up a new certificate, but that only works if entire cohorts - in the original meaning of the word - start the course together and not at different times. Which is exactly why this plugin exists, as I understand...)

**Comment by danmarsden** [comment]
No plans on my end - typically "feature development" is something that is only completed when someone funds the development effort. I've commented previously in other threads but I think any form of "recompletion" when it comes to certificate plugins should really be built and supported within the certificate plugin as re-issueing certificates and keeping track of previous ones seems to be something that is logical to support within the certificate plugin itself.

so... if you want to fund development - I'd suggest you look at doing this within the cert plugins first, then adding support in local_recompletion to help trigger that process.

**Comment by danmarsden** [comment]
I've just merged in a patch for mod_customcert plugin so I'm closing this issue for now - however happy if others want to add issues for supporting other cert plugins like tool_certificate/mod_coursecertificate etc.
