### ISSUE TITLE
reset clears all assignment and course data

### ISSUE THREAD

**Issue by Beansworthy** [danmarsden/moodle-local_recompletion#75]
Hi Dan and team,

Thanks for your work developing this plugin!  I'm not sure if this is intended behaviour, but I couldn't recognise anything in the documentation. 

Once an expiration triggers a course reset, all course and assignment data for the student is cleared - assignment status, assignment grade, all dates, file submissions, comments, feedback files, feedback notes, final grade, completion status...

The activity settings which appear to cause this are:

Activity Settings: Submission settings: **Additional Attempts:** **Automatic until pass**
Activity Settings: Submission settings: **Maximum Attempts:** **Unlimited**

I was finally able to retain data by changing 
 **Additional Attempts: **Manual**
 Maximum Attempts: **1****

**Comment by danmarsden** [comment]
I suspect you will find the data for the physical assignment might still exist, but that the Moodle assignment activity UI is hiding it - try looking at the db layer, or adjusting the moodle assignment settings after the recompletion and you might find it re-appearing in the assignment UI.

in any case - happy for funding or pull requests to improve how it works - thanks!

**Comment by Beansworthy** [comment]
For my purposes, changing the submission settings to manual and 1 is fine, just flagging in case it's unintentional.
 Thanks!

**Comment by danmarsden** [comment]
closing this as it's not quite clear what is being asked for as an improvement here - happy if someone wants to create a new issue that covers something specific though!
