### ISSUE TITLE
html placeholders are not working in the Notification body - Release 2023040300 (2023040301)

### ISSUE THREAD

**Issue by ShirleyGregorczyk** [danmarsden/moodle-local_recompletion#76]
We updated our LMS to release 2023040300 (2023040301). 
Our notifications no longer behave as expected. 
The placeholders within the body are not adding the expected values. The subject line is working as expected. 
The body displays correctly until the reveal html is selected. 
When I displayed the body in html the -> was replaced with `&gt;`               
I have tried multiple times to replace the &gt; with -> and save the notification. 
When I open the notification in html it is displayed with the &gt; values.
This affects 49 courses to hundreds of students.

**Comment by danmarsden** [comment]
ug - that sounds horrible! - sorry @ShirleyGregorczyk - it sounds like a regression caused by #66 - @glepod is this something you might be able to revisit and fix? - I'm not sure I'll have time to look at it myself in the next few weeks.
