### ISSUE TITLE
Quiz user overrides not reset

### ISSUE THREAD

**Issue by QueenslandMoodler** [danmarsden/moodle-local_recompletion#77]
We have some courses which use local_recompletion where learners have a limited number of attempts on a quiz and are then required to speak to their educator who may choose to give them extra attempts.

When Recompletion is engaged, all quiz attempts are deleted but the user overrides remain, so instead of getting the x attempts they should get getting, they get x+n.

**Comment by danmarsden** [comment]
Thanks for the report - probably needs an extra setting in the quiz recompletion settings - I can imagine some cases where the user overrides should not be cleared. Pull requests and or funding for feature development are always welcome!

**Comment by QueenslandMoodler** [comment]
Thanks Dan. Having it as a setting that can be toggled would work well. We'll have a talk at our end as to whether we've got the skills/funding to support this enhancement. If not us, then hopefully somebody will be able to contribute!

**Comment by danmarsden** [comment]
fixed in #175
