### ISSUE TITLE
recompletion does not remove viewed state

### ISSUE THREAD

**Issue by rafdel1** [danmarsden/moodle-local_recompletion#78]
When resetting course completion, any module item configured to "_Student must view this activity to complete it_" will not reset.
This causes any module items depending on it not to trigger the "new" viewed state thus leaving students "stuck" with a "Done" module item BUT the next item will not unlock.

Viewed states are stored in the **course_modules_viwed** table

Request adding the following line after line 122:
Line122 $DB->delete_records_select('course_modules_completion', $selectsql, $params);
Line123 $DB->delete_records_select('course_modules_viewed', $selectsql, $params);

**Comment by blanderson22** [comment]
We have this issue as well, and I think it may be broader than just the viewed state for access restrictions settings. In our case the activity completion is set to _"Show as complete when user makes a choice"_. This leaves our students stuck because of the same reason. The choice activity shows that it's complete but the dependent module remains locked.

**Comment by rafdel1** [comment]
You may want to check both tables referenced in the request to see if there are entries for your students that were reset. If there are entries in either table, the module will not unlock.

-> course_modules_completion
-> course_modules_viewed

**Comment by blanderson22** [comment]
I don't have a course_modules_viewed table. I do have a "viewed" column in the course_modules_completion table.

**Comment by blanderson22** [comment]
The only way we've been able to resolve it, short of modifying the database directly, is to visit the activity completion report and mark the activities as complete and then remove it again. That 'resets' the completion state that the student sees in the course and the dependent restrictions rely on to allow access to other dependent activities.

**Comment by blanderson22** [comment]
We're using Moodle 3.11 so maybe that's why we don't have a course_modules_viewed table. Based on my testing, what needs to happen in Moodle 3.11 is that the course_modules_completion table record needs to be removed, or the completionstate and viewed columns need to be set back to 0.

**Comment by danmarsden** [comment]
Thanks for all the extra info! - pull requests are always welcome :-)

**Comment by mhughes2k** [comment]
I've done a (draft) PR that removes the course_modules_viewed records as well (it should also archive them).

I've also done a bit to remove the copy & paste part for getting the config, as there were notices about undefined properties coming up, and consolidated this in to a single local_recomplete_get_config() function, that will generate a "sensible" default if there is *no* configuration in the database.

This probably needs extended to handle when there are *some* configuration values set...

**Comment by danmarsden** [comment]
Thanks @mhughes2k - probably also needs the privacy api class updated with details on the new table - nice idea to have a new get_config() function too. -  I don't have a lot of free time at the moment, but if you end up finishing this off and adding privacy class api updates just let me know and I'll come back and take a look!!!

**Comment by mhughes2k** [comment]
I've done a push with the privacy API implemented, and a few coding standard things.

**Comment by danmarsden** [comment]
thanks - failing a few codechecker things but I've merged it in and will drop a fix up commit on top.

**Comment by mhughes2k** [comment]
Damnit! I was trying really hard to hit the coding standards :-)

Thanks!
