### ISSUE TITLE
Fatal error in task execution

### ISSUE THREAD

**Issue by anieminen** [danmarsden/moodle-local_recompletion#9]
Hi,

I've noticed a fatal error while testing the plugin and running cron:

> Execute scheduled task: Check for users that need to recomplete (local_recompletion\task\check_recompletion)
PHP Fatal error:  Class 'completion_info' not found in /var/www/moodle/local/recompletion/classes/task/check_recompletion.php on line 52

**Comment by danmarsden** [comment]
Thanks Arto, what Moodle version are you using?

**Comment by anieminen** [comment]
I'm using Moodle 3.1.7+.

**Comment by danmarsden** [comment]
I don't think I've done any testing on 3.1 - only 3.3 and higher. Feel free to help us work on this by improving the plugin and submitting a pull request or get in touch if you might be able to help with funding. thanks for the report!

**Comment by anieminen** [comment]
I'm getting the same - and also found another "undefined function" error - when testing with latest Moodle 3.3.2+. It seems that a couple of library files have to be included to fix those. I'll try to make a pull request soon.

**Comment by anieminen** [comment]
Fix in pull request #10

**Comment by danmarsden** [comment]
cool - thanks!
