### ISSUE TITLE
Trigger re-completion on a course unenrollment 

### ISSUE THREAD

**Issue by dmitriim** [danmarsden/moodle-local_recompletion#94]
In my case I'd like to clean up completion after users are unenrolled from a course. Would be nice to add a new recompletion type "After unenrollment"

**Comment by danmarsden** [comment]
I'm not quite sure about this being it's own type, I think there are some cases where a site would like to use both time-based recompletion but also trigger a reset of the users data if they are un-enrolled.

I also have a client who has asked in the past about clearing user data on un-enrollment so I'd be keen to see this in the plugin too.!

**Comment by dmitriim** [comment]
If not it's own type then what? A new global setting + extra setting on a course level? 

![image](https://github.com/danmarsden/moodle-local_recompletion/assets/4626431/fcb2350f-770d-4592-a131-9c28aa47a9a6)

**Comment by danmarsden** [comment]
yeah - just a new setting under the type - if the recompletion is enabled - some controls that let you say "also trigger on user un-enrolment" 

but - I wouldn't block inclusion in the core release if it was a new "type" on it's own - it would just be handy if it wasn't a type and gave us more flexibility to use it no matter what recompletion type was in use.

**Comment by dmitriim** [comment]
Closing as completed.
