### ISSUE TITLE
Access archived records through UI

### ISSUE THREAD

**Issue by dmitriim** [danmarsden/moodle-local_recompletion#95]
Would be nice to implement a couple of reports to access archived data through UI.

Entities and data sources for following tables:

- [x]  local_recompletion_cc - archive of course_completions table
- [x] local_recompletion_cmc - archive of course_modules_completion table
- [x] local_recompletion_qa - archive of quiz attempts table
- [x] local_recompletion_qg - archive of quiz grades table
- [x] local_recompletion_h5p - Users attempts inside H5P activities (h5pactivity_attempts)

**Comment by danmarsden** [comment]
definitely! - although I don't really want to create old style reports - ideally all new reporting should use reportbuilder sources, allowing the admin to set up a cusomt report that meets their needs.
